# Generated by Django 5.0.4 on 2024-05-05 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='fulfillment_rete',
            new_name='fulfillment_rate',
        ),
    ]
